In [1]:
import camelot
import pandas as pd
import openpyxl
import os
import tkinter
# tables = camelot.read_pdf('epd1388_2021.pdf', pages='10',process_background=True)
# tables = camelot.read_pdf('./IBU-09-20/New/14632.pdf', pages='6', split_text=True,table_areas=["69.60548391889084,500.088593765987,525.3099336281931,403.96614296894364"])
# print(len(tables))

# tables = camelot.read_pdf('./New/14699.pdf', pages='all')
# print(len(tables))

In [2]:
%%javascript
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

In [3]:
files = os.listdir('./Files')
files = ['epd1203.pdf', '']
for file_name in files:
    try:
        tables = camelot.read_pdf('./Files/'+file_name, pages='all') # , process_background = True
        print(file_name)
        for table in tables:
            print("Text: ")
            camelot.plot(table, kind='text').show()
            print("Grid: ")
            camelot.plot(table, kind='grid').show()
            print("Line: ")
            camelot.plot(table, kind='line').show()
            print("Conture: ")
            camelot.plot(table, kind='contour').show()
            print("Join: ")
            camelot.plot(table, kind='joint').show()
    except:
        print("Doslo do greske prilikom citanja za " + str(file_name))

Doslo do greske prilikom citanja za epd1203.pdf
Doslo do greske prilikom citanja za

In [6]:
len(os.listdir('./Files/all'))

48

In [ ]:
files = os.listdir('./Files/all')
#files = ['epd4044.pdf', 'epd4051.pdf', 'epd4054.pdf','epd4061.pdf']

r = []
for file in files:
    try:
        tables = camelot.read_pdf('./Files/' + file, pages='all')

        print("************ FILE NAME: " + file + " ****************")
        dataFrames = []
        file_info = {}
        stages = []
        for table in tables:
            df = table.df
#             gwp = ['GWP-total', 'GWP-tot','Global \nuppvärmningspotential \n(GWP)', 'GWP - Total', 'Global warming potential', 'GWP', 'Globales Erwärmungspotenzial ­ total', 'Globales Erwärmungspotenzial']
#             for g in gwp:
#                 if (g in df.values) and ('TRACI 2.1 Impact Assessment' not in df.values):
#                     try:
#                         #df = df.rename(columns=df.iloc[0])
#                         dataFrames.append(df)
#                     except:
#                         dataFrames.append(df)
            search_gwp = ['^.*Global.*$', '^.*GWP.*$' ]
            if not df[df[0].str.contains('|'.join(search_gwp)) | df[1].str.contains('|'.join(search_gwp)) | df[2].str.contains('|'.join(search_gwp))].empty:
            
                dataFrames.append(df)

            pere = ['PERE', 'Renewable primary energy as energy carrier', 'Erneuerbare Primärenergie als Energieträger']
            for p in pere:
                if p in df.values:
                    try:
                        #df = df.rename(columns=df.iloc[0])
                        dataFrames.append(df)
                    except:
                        dataFrames.append(df)

            hwd = ['HWD', 'Hazardous waste disposed', 'Gefährlicher Abfall zur Deponie']
            for h in hwd:
                if h in df.values:
                    try:
                        #df = df.rename(columns=df.iloc[0])
                        dataFrames.append(df)
                    except:
                        dataFrames.append(df)


#         try:
#             rez = []
#             for list in df[df.eq('Unit').any(1)].values:
#                 rez = rez + list.tolist()
#             longest_list = []
#             help = [longest_list.append(x) for x in rez if x not in longest_list]

#             droped_nan = [e for e in longest_list if str(e) != 'nan']


#             unit_index = droped_nan.index('Unit') + 1
#             stages = droped_nan[unit_index:]
#             print(stages)
#         except:
#     #         a = list(df[df.eq('Einheit').any(1)].values[0])
#     #         unit_index = a.index('Einheit') + 1
#     #         stages = a[unit_index:]
#             stages = "NOT FOUND"





        #result = pd.concat(dataFrames)
    #     file_info["dataFrame"] = dataFrames        
    #     file_info["file_name"] = file
    #     file_info["stages"] = stages
        if dataFrames:
            file_info["dataFrame"] = pd.concat(dataFrames)        
            file_info["file_name"] = file
#             file_info["stages"] = stages

            r.append(file_info)
        else:
            try:
                tables = camelot.read_pdf('./Files/' + file, pages='all', process_background=True)
                dataFrames = []
                file_info = {}
                stages = []
                for table in tables:
                    df = table.df

                    #dataFrames = []
                    #gwp = ['GWP-total', '' 'Global \nuppvärmningspotential \n(GWP)','GWP-tot', 'GWP - Total', 'Global warming potential', 'GWP', 'Globales Erwärmungspotenzial ­ total', 'Globales Erwärmungspotenzial']
                    #for g in gwp:
#                         if (g in df.values) and ('TRACI 2.1 Impact Assessment' not in df.values):
                    search_gwp = ['^.*Global.*$', '^.*GWP.*$' ]
                    if not df[df[0].str.contains('|'.join(search_gwp)) | df[1].str.contains('|'.join(search_gwp)) | df[2].str.contains('|'.join(search_gwp))].empty:
            
                        dataFrames.append(df)
#                         try:
#                             df = df.rename(columns=df.iloc[0])
#                             dataFrames.append(df)
#                         except:
#                             dataFrames.append(df)

                    pere = ['PERE', 'Renewable primary energy as energy carrier', 'Erneuerbare Primärenergie als Energieträger']
                    for p in pere:
                        if p in df.values:
                            dataFrames.append(df)
#                             try:
#                                 df = df.rename(columns=df.iloc[0])
#                                 dataFrames.append(df)
#                             except:
#                                 dataFrames.append(df)

                    hwd = ['HWD', 'Hazardous waste disposed', 'Gefährlicher Abfall zur Deponie']
                    for h in hwd:
                        if h in df.values:
                            dataFrames.append(df)
#                             try:
#                                 df = df.rename(columns=df.iloc[0])
#                                 dataFrames.append(df)
#                             except:
#                                 dataFrames.append(df)

                if dataFrames:
                    file_info["dataFrame"] = pd.concat(dataFrames)         
                    file_info["file_name"] = file
                else:
                    print("Noting to ADD!")
            except:
                print("Ne moze procitati")              
    except:
        print("Ne moze procitati")
    #write_to_excel(dataFrame, stages)

# make_excel_file(r)

# print(types)
# r

************ FILE NAME: epd1203.pdf ****************
Ne moze procitati
************ FILE NAME: epd1729.pdf ****************
Ne moze procitati
Ne moze procitati
Ne moze procitati

In [3]:
files = os.listdir('./Files/all')

r = []
for file in files:
    try:

        tables = camelot.read_pdf('./Files/' + file, pages='all')

        print("************ FILE NAME: " + file + " ****************")
        dataFrames = []
        file_info = {}
        stages = []
        for table in tables:
            df = table.df
            search_gwp = ['^Global.*$', '^.*Global.*$', '^.*GWP.*$', 'Global', 'GWP', '(GWP)', '^.*(GWP).*$']
            if len(df.columns) > 3:
                if not df[df[0].str.contains('|'.join(search_gwp)) | df[1].str.contains('|'.join(search_gwp)) | df[2].str.contains('|'.join(search_gwp))].empty:
                    dataFrames.append(df)

            pere = ['PERE', 'Renewable primary energy as energy carrier', 'Erneuerbare Primärenergie als Energieträger']
            for p in pere:
                if p in df.values:
                    try:
                        #df = df.rename(columns=df.iloc[0])
                        dataFrames.append(df)
                    except:
                        dataFrames.append(df)

            hwd = ['HWD', 'Hazardous waste disposed', 'Gefährlicher Abfall zur Deponie']
            for h in hwd:
                if h in df.values:
                    try:
                        #df = df.rename(columns=df.iloc[0])
                        dataFrames.append(df)
                    except:
                        dataFrames.append(df)

        if dataFrames:
            file_info["dataFrame"] = pd.concat(dataFrames)        
            file_info["file_name"] = file

            r.append(file_info)
        else:
            try:
                tables = camelot.read_pdf('./Files/' + file, pages='all', process_background=True)
                dataFrames = []
                file_info = {}
                stages = []
                for table in tables:
                    df = table.df
                    search_gwp = ['^Global.*$', '^.*Global.*$', '^.*GWP.*$', 'Global', 'GWP', '(GWP)', '^.*(GWP).*$']
                    if len(df.columns) > 3:
                        if not df[df[0].str.contains('|'.join(search_gwp)) | df[1].str.contains('|'.join(search_gwp)) | df[2].str.contains('|'.join(search_gwp))].empty:
                            dataFrames.append(df)

                    pere = ['PERE', 'Renewable primary energy as energy carrier', 'Erneuerbare Primärenergie als Energieträger']
                    for p in pere:
                        if p in df.values:
                            dataFrames.append(df)


                    hwd = ['HWD', 'Hazardous waste disposed', 'Gefährlicher Abfall zur Deponie']
                    for h in hwd:
                        if h in df.values:
                            dataFrames.append(df)


                if dataFrames:
                    file_info["dataFrame"] = pd.concat(dataFrames)         
                    file_info["file_name"] = file
                else:
                    print("Noting to ADD!")
            except:
                print("Ne moze procitati proccess back ground")              
    except:
        print("Ne moze procitati")
    #write_to_excel(dataFrame, stages)

# make_excel_file(r)

# print(types)
# r

************ FILE NAME: epd1203.pdf ****************

C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

************ FILE NAME: epd1729.pdf ****************

C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)
C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

************ FILE NAME: epd1891.pdf ****************

C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)
C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

Noting to ADD!
************ FILE NAME: epd2113.pdf ****************

C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

************ FILE NAME: epd2119.pdf ****************

C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)
C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

************ FILE NAME: epd2147.pdf ****************

C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)
C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

************ FILE NAME: epd2250.pdf ****************

C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)
UserWarning:   (524.5, 527.26888) does not lie in column range (468.1306378476421, 524.2943168077388) [utils.py:740]
C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

************ FILE NAME: epd2251.pdf ****************

C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)
UserWarning:   (524.5, 527.26888) does not lie in column range (468.1343870918985, 524.0543651753326) [utils.py:740]
UserWarning:   (541.9, 544.66888) does not lie in column range (485.4109046251512, 541.8107859733979) [utils.py:740]
C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

************ FILE NAME: epd2270.pdf ****************

C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

************ FILE NAME: epd2283.pdf ****************

C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)
C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

************ FILE NAME: epd2328.pdf ****************

C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

Noting to ADD!
Ne moze procitati
************ FILE NAME: epd2837.pdf ****************

C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)
UserWarning:   (570.36, 572.862) does not lie in column range (69.46599758162031, 570.1250785973398) [utils.py:740]
UserWarning:   (524.26, 527.02888) does not lie in column range (527.2337243047159, 582.152654171705) [utils.py:740]
UserWarning:   (524.74, 526.9751200000001) does not lie in column range (527.2337243047159, 582.152654171705) [utils.py:740]
C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

Ne moze procitati
Ne moze procitati
************ FILE NAME: epd351.pdf ****************

C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)
C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

Ne moze procitati
Ne moze procitati
Ne moze procitati
Ne moze procitati
Ne moze procitati
Ne moze procitati
Ne moze procitati
Ne moze procitati
Ne moze procitati
Ne moze procitati
Ne moze procitati
Ne moze procitati
Ne moze procitati
************ FILE NAME: epd414.pdf ****************

C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

Noting to ADD!
Ne moze procitati
Ne moze procitati
************ FILE NAME: epd442.pdf ****************

C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)
C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

Noting to ADD!
************ FILE NAME: epd454.pdf ****************
Ne moze procitati
Ne moze procitati
Ne moze procitati
Ne moze procitati
Ne moze procitati
Ne moze procitati
Ne moze procitati
Ne moze procitati

C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

************ FILE NAME: epd665.pdf ****************
Noting to ADD!
************ FILE NAME: epd666.pdf ****************
Noting to ADD!
************ FILE NAME: epd667.pdf ****************
Noting to ADD!
************ FILE NAME: epd992.pdf ****************

C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)
C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

************ FILE NAME: epd993.pdf ****************

C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)
C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

************ FILE NAME: epd994.pdf ****************

C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)
C:\Users\mirol\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

In [6]:

tables = camelot.read_pdf('./Files/epd1203.pdf', pages='all')
print(len(tables))

29

In [14]:
t = tables[6].df
t

,0,1,2,3,4,5,6
0,1 m3 White i.idro DRAIN,,,,,,
1,Environmental \nImpacts,Units,A1-A3,A4,A5,B1,B2-B7
2,GWP-tot,kg CO2 eq,4.13E2,4.98E0,1.99E1,-1.19E1,-
3,GWP-fos,kg CO2 eq,4.12E2,4.97E0,1.99E1,-1.19E1,-
4,GWP-bio,kg CO2 eq,1.47E-1,1.75E-3,8.99E-3,0.00,-
5,GWP-luc,kg CO2 eq,1.22E-1,1.89E-3,7.35E-3,0.00,-
6,ODP,kg CFC-11 eq,2.08E-5,9.03E-7,1.98E-6,0.00,-
7,POCP,Kg NMVOC eq.,1.25E0,1.48E-2,1.12E-1,0.00,-
8,AP,mol H+ eq.,1.69E-1,1.20E-3,8.84E-3,0.00,-
9,EP-fw,kg PO4\n3- eq.,5.50E-2,3.92E-4,2.88E-3,0.00,-
10,EP-fw*,kg P eq,3.98E-3,3.28E-5,7.59E-4,0.00,-
11,EP-mar,kg N eq.,3.38E0,2.96E-2,4.06E-1,0.00,-
12,EP-ter,mol N eq.,8.82E-1,1.16E-2,1.11E-1,0.00,-
13,ADPE,kg Sb eq,4.45E-4,1.48E-5,2.04E-5,0.00,-
14,ADPF,Mj eq,2.47E3,7.37E1,1.85E2,0.00,-
15,WDP,m3,3.60E3,5.20E-1,1.06E2,0.00,-

In [16]:
t[0][2]

'GWP-tot'

In [58]:

tables = camelot.read_pdf('./Files/epd442.pdf', pages='all',   flavor='stream' )#process_background=True
print(len(tables))

UserWarning: No tables found in table area 1 [stream.py:365]

84

In [50]:
t = tables[0].df
t

,0,1,2,3,4,5,6
0,USE OF \nUNIT\nRESOURCES,UPSTREAM\nCORE\nDOWNSTREAM\nPri,,ma,ry,,TOTAL
1,,,,,,,
2,,,,,,,
3,,,,,,,
4,,,,,,,
5,,Ingredients \nPackaging \nWheat \nproduction\n...,Flour \nDistribution\npac\nproduction\nend,kag\n of,i\nl,ng \nife,
6,"MJ, net calorific \nUse as energy carrier\nval...","2,34E-02\n2,37E-01\n1,38E-03\n0,00E+00\n1,38E-...","3,76E-01\n1,75E-03\n3,2",6E-\n0E+\n6E-,,05\n00\n05,"6,39E-01\n1,38E-01\n7,78E-01"
7,,,,,,,
8,,"2,34E-02\n3,75E-01\n1,38E-03","3,76E-01\n1,75E-03\n3,2",,,,
9,"MJ, net calorific \nUse as energy carrier\nval...","1,40E+00\n1,97E-01\n9,63E-01\n0,00E+00\n0,00E+...","4,20E-04\n1,22E+00\n1,6",3E-\n0E+\nE-,,04\n00\n04,"3,78E+00\n0,00E+00\n3,78E+00"
10,,,,,,,
11,,"1,40E+00\n1,97E-01\n9,63E-01","4,20E-04\n1,22E+00\n1,63",,,,
12,Secondary material\nkg,"0,00E+00\n0,00E+00\n0,00E+00\n0,00E+00\n0,00E+...",,E+,,00,"0,00E+00"
13,"MJ, net calorific \nRenewable secondary fuels\...","0,00E+00\n0,00E+00\n0,00E+00\n0,00E+00\n0,00E+...",,E+,,00,"0,00E+00"
14,"MJ, net calorific \nNon-renewable secondary fu...","0,00E+00\n0,00E+00\n0,00E+00\n0,00E+00\n0,00E+...",,E+,,00,"0,00E+00"
15,Net use of fresh water\nm3,"1,21E-02\n4,98E-04\n8,00E-05\n2,91E-03\n2,47E-...",,2E-,,07,"1,56E-02"

type(r)

In [11]:
type(r)

list

In [4]:
len(r)

4

In [6]:
for i in range(0,4):
    try:
        tables = camelot.read_pdf('./Files/epd2765.pdf', pages='all')
        print(len(tables))
    except:
        
    print(i)

0
1
2
3

In [7]:
len(r)

4

In [14]:
d = r[3]['dataFrame'][0]
d.head()

,GWP,"Fossil\n91,10\n11,29\n20,03\nBiogenic\n7,16\n0,03\n19,88\ng CO2eq\nLULUC\n0,23\n0,00\n0,00\nTotal\n98,49\n11,32\n39,91","122,42\n27,08\n0,23\n149,72\n0,40\n0,14\n0,50\n0,86\n2,21\n0,03"
0,GWP,"Fossil\n91,10\n11,29\n20,03\nBiogenic\n7,16\n0...","122,42\n27,08\n0,23\n149,72\n0,40\n0,14\n0,50\..."
1,AP\nEP\nPOFP\nADP – Elements\nADP – Fossil fue...,"0,30\n0,08\n0,02\ng SO2eq\n3-\n0,11\n0,01\n0,0...",

In [6]:
for fr in r:
    display(fr['dataFrame'])

,0,1,2,3,4,5,6
0,1 m3 White i.idro DRAIN,,,,,,
1,Environmental \nImpacts,Units,A1-A3,A4,A5,B1,B2-B7
2,GWP-tot,kg CO2 eq,4.13E2,4.98E0,1.99E1,-1.19E1,-
3,GWP-fos,kg CO2 eq,4.12E2,4.97E0,1.99E1,-1.19E1,-
4,GWP-bio,kg CO2 eq,1.47E-1,1.75E-3,8.99E-3,0.00,-
...,...,...,...,...,...,...,...
0,1 m3 Grey i.idro DRAIN,,,,,,
1,Waste,Units,C1,C2,C3,C4,D
2,HWD,kg,0.00,0.00,0.00,0.00,0.00
3,NHWD,kg,0.00,0.00,0.00,0.00,0.00
4,RWD,kg,-,-,-,-,-

,0,1,2,3,4,5,6,7
0,PARAMETER,,UNIT,Upstream,Core,TOTAL\nat gate,Downstream,TOTAL
1,Global warming \npotential (GWP),Fossil,kg CO2 eq.,"3,39*10-2","4,63*10-3","3,86*10-2","3,17*10-2","7,03*10-2"
2,,Biogenic,kg CO2 eq.,"1,15*10-3","4,32*10-5","1,19*10-3","5,42*10-6","1,20*10-3"
3,,Land use and land \ntransformation,kg CO2 eq.,"2,35*10-5","8,66*10-7","2,44*10-5","4,98*10-6","2,94*10-5"
4,,TOTAL,kg CO2 eq.,"3,51*10-2","4,68*10-3","3,98*10-2","3,17*10-2","7,15*10-2"
5,Acidification potential (AP),,kg SO2 eq.,"1,19*10-4","1,74*10-5","1,36*10-4","7,38*10-5","2,10*10-4"
6,Eutrophication potential (EP),,3- eq.\nkg PO4,"6,70*10-5","7,23*10-6","7,42*10-5","3,19*10-5","1,06*10-4"
7,Formation potential of tropospheric \nozone (P...,,kg NMVOC eq.,"9,42*10-5","1,25*10-5","1,07*10-4","7,88*10-5","1,86*10-4"
8,Abiotic depletion potential – Elements,,kg Sb eq.,"6,49*10-8","6,45*10-9","7,14*10-8","4,67*10-8","1,18*10-7"
9,Abiotic depletion potential \nFossil resources,,"MJ, net calorific \nvalue","0,443","0,065","0,508","0,205","0,712"
10,Water scarcity potential,,m3 eq.,"8,32*10-3","9,45*10-4","9,27*10-3","2,34*10-3","1,16*10-2"
0,PARAMETER,,UNIT,Upstream,Core,TOTAL\nat gate,Downstream,TOTAL
1,Global warming \npotential (GWP),Fossil,kg CO2 eq.,"3,30*10-2","4,58*10-3","3,76*10-2","9,89*10-3","4,75*10-2"
2,,Biogenic,kg CO2 eq.,"1,08*10-3","3,86*10-5","1,12*10-3","4,86*10-6","1,12*10-3"
3,,Land use and land \ntransformation,kg CO2 eq.,"2,34*10-5","8,54*10-7","2,42*10-5","4,06*10-6","2,83*10-5"
4,,TOTAL,kg CO2 eq.,"3,41*10-2","4,62*10-3","3,88*10-2","9,90*10-3","4,87*10-2"
5,Acidification potential (AP),,kg SO2 eq.,"1,17*10-4","1,74*10-5","1,34*10-4","1,06*10-4","2,39*10-4"
6,Eutrophication potential (EP),,3- eq.\nkg PO4,"6,55*10-5","7,09*10-6","7,25*10-5","1,53*10-5","8,79*10-5"
7,Formation potential of tropospheric \nozone (P...,,kg NMVOC eq.,"9,06*10-5","1,28*10-5","1,03*10-4","9,3*10-5","1,96*10-4"
8,Abiotic depletion potential – Elements,,kg Sb eq.,"6,12*10-8","6,63*10-9","6,79*10-8","2,71*10-8","9,5*10-8"
9,Abiotic depletion potential \nFossil resources,,"MJ, net calorific \nvalue","0,430","0,064","0,494","0,136","0,630"
10,Water scarcity potential,,m3 eq.,"7,86*10-3","9,13*10-4","8,77*10-3","8,99*10-4","9,67*10-3"
0,PARAMETER,UNIT,Upstream,Core,TOTAL\nat gate,Downstream,TOTAL,NaN
1,Hazardous waste disposed,kg,"1,22*10-6","1,04*10-6","2,26*10-6","1,54*10-7","2,41*10-6",NaN
2,Non-hazardous waste disposed,kg,"1,37*10-2","1,03*10-3","1,48*10-2","1,15*10-2","2,62*10-2",NaN
3,Radioactive waste disposed,kg,"1,62*10-6","2,4*10-7","1,86*10-6","1,42*10-6","3,28*10-6",NaN
0,PARAMETER,UNIT,Upstream,Core,TOTAL\nat gate,Downstream,TOTAL,NaN
1,Hazardous waste disposed,kg,"1,2*10-6","9,42*10-7","2,14*10-6","9,81*10-8","2,24*10-6",NaN
2,Non-hazardous waste disposed,kg,"1,26*10-2","1,07*10-3","1,36*10-2","3,02*10-3","1,67*10-2",NaN
3,Radioactive waste disposed,kg,"1,59*10-6","2,48*10-7","1,84*10-6","9,66*10-7","2,8*10-6",NaN

,0,1,2,3,4,5,6,7,8,9,10
0,Parameter \nAbbreviation \nUnits,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Environmental impacts,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Climate change – GWP fossil,GWP-fossil,kg CO2 eq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Climate change – GWP biogenic,GWP-biogenic,kg CO2 eq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Climate change – GWP land transformation,GWP-luluc,kg CO2 eq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
4,,,Unit,A1 - A3,A4,A5,C1,C2,C3,C4,D
5,,CFR,kg,0.00E+00,0.00E+00,0.00E+00,0.00E+00,0.00E+00,0.00E+00,0.00E+00,0.00E+00
6,,MFR,kg,2.51E-03,2.00E-04,6.23E-04,4.79E-05,1.34E-04,0.00E+00,1.73E-04,0.00E+00
7,,MER,kg,1.70E-04,0.00E+00,4.09E-05,2.13E-06,2.31E-06,0.00E+00,5.79E-07,0.00E+00
8,,EE,MJ,0.00E+00,0.00E+00,2.84E-02,0.00E+00,0.00E+00,0.00E+00,2.84E+00,0.00E+00

                0               1                  2                 3
0                  BCF PA6 \n(1C)  BCF PA6 \n(2E+2F)  BCF PA6.6 \n(3C)
1     GWP – Total        8,65E+00           9,02E+00          8,00E+00
2    GWP – Fossil        8,58E+00           8,87E+00          7,90E+00
3  GWP – Biogenic        7,53E-02           1,43E-01          9,56E-02
4     GWP – Luluc        2,72E-03           2,44E-03          4,18E-03
5       GWP – GHG        8,58E+00           8,88E+00          7,90E+00

In [14]:
r[2]

{'dataFrame':                                           0             1          2   \
 0           Parameter \nAbbreviation \nUnits
 1                      Environmental impacts
 2                Climate change – GWP fossil    GWP-fossil  kg CO2 eq
 3              Climate change – GWP biogenic  GWP-biogenic  kg CO2 eq
 4   Climate change – GWP land transformation     GWP-luluc  kg CO2 eq
 ..                                       ...           ...        ...
 4                                                                Unit
 5                                                      CFR         kg
 6                                                      MFR         kg
 7                                                      MER         kg
 8                                                       EE         MJ

           3         4         5         6         7         8         9   \
 0        NaN       NaN       NaN       NaN       NaN       NaN       NaN
 1        NaN       NaN       NaN       NaN       NaN       NaN       NaN
 2        NaN       NaN       NaN       NaN       NaN       NaN       NaN
 3        NaN       NaN       NaN       NaN       NaN       NaN       NaN
 4        NaN       NaN       NaN       NaN       NaN       NaN       NaN
 ..       ...       ...       ...       ...       ...       ...       ...
 4    A1 - A3        A4        A5        C1        C2        C3        C4
 5   0.00E+00  0.00E+00  0.00E+00  0.00E+00  0.00E+00  0.00E+00  0.00E+00
 6   2.51E-03  2.00E-04  6.23E-04  4.79E-05  1.34E-04  0.00E+00  1.73E-04
 7   1.70E-04  0.00E+00  4.09E-05  2.13E-06  2.31E-06  0.00E+00  5.79E-07
 8   0.00E+00  0.00E+00  2.84E-02  0.00E+00  0.00E+00  0.00E+00  2.84E+00

           10
 0        NaN
 1        NaN
 2        NaN
 3        NaN
 4        NaN
 ..       ...
 4          D
 5   0.00E+00
 6   0.00E+00
 7   0.00E+00
 8   0.00E+00

 [177 rows x 11 columns],
 'file_name': 'epd2270.pdf'}

In [8]:
r

[{'dataFrame':                            0          1        2        3        4        5  \
  0    1 m3 White i.idro DRAIN
  1   Environmental  \nImpacts      Units    A1-A3       A4       A5       B1
  2                    GWP-tot  kg CO2 eq   4.13E2   4.98E0   1.99E1  -1.19E1
  3                    GWP-fos  kg CO2 eq   4.12E2   4.97E0   1.99E1  -1.19E1
  4                    GWP-bio  kg CO2 eq  1.47E-1  1.75E-3  8.99E-3     0.00
  ..                       ...        ...      ...      ...      ...      ...
  0     1 m3 Grey i.idro DRAIN
  1                      Waste      Units       C1       C2       C3       C4
  2                        HWD         kg     0.00     0.00     0.00     0.00
  3                       NHWD         kg     0.00     0.00     0.00     0.00
  4                        RWD         kg        -        -        -        -

          6
  0
  1   B2-B7
  2       -
  3       -
  4       -
  ..    ...
  0
  1       D
  2    0.00
  3    0.00
  4       -

  [158 rows x 7 columns],
  'file_name': 'epd1203.pdf'},
 {'dataFrame':                                                     0  \
  0                                           PARAMETER
  1                    Global warming \npotential (GWP)
  2
  3
  4
  5                        Acidification potential (AP)
  6                       Eutrophication potential (EP)
  7   Formation potential of tropospheric \nozone (P...
  8              Abiotic depletion potential – Elements
  9     Abiotic depletion potential  \nFossil resources
  10                           Water scarcity potential
  0                                           PARAMETER
  1                    Global warming \npotential (GWP)
  2
  3
  4
  5                        Acidification potential (AP)
  6                       Eutrophication potential (EP)
  7   Formation potential of tropospheric \nozone (P...
  8              Abiotic depletion potential – Elements
  9     Abiotic depletion potential  \nFossil resources
  10                           Water scarcity potential
  0                                           PARAMETER
  1                            Hazardous waste disposed
  2                        Non-hazardous waste disposed
  3                          Radioactive waste disposed
  0                                           PARAMETER
  1                            Hazardous waste disposed
  2                        Non-hazardous waste disposed
  3                          Radioactive waste disposed

                                       1                          2          3  \
  0                                                            UNIT   Upstream
  1                               Fossil                 kg CO2 eq.  3,39*10-2
  2                             Biogenic                 kg CO2 eq.  1,15*10-3
  3   Land use and land \ntransformation                 kg CO2 eq.  2,35*10-5
  4                                TOTAL                 kg CO2 eq.  3,51*10-2
  5                                                      kg SO2 eq.  1,19*10-4
  6                                                  3- eq.\nkg PO4  6,70*10-5
  7                                                    kg NMVOC eq.  9,42*10-5
  8                                                       kg Sb eq.  6,49*10-8
  9                                       MJ, net calorific \nvalue      0,443
  10                                                         m3 eq.  8,32*10-3
  0                                                            UNIT   Upstream
  1                               Fossil                 kg CO2 eq.  3,30*10-2
  2                             Biogenic                 kg CO2 eq.  1,08*10-3
  3   Land use and land \ntransformation                 kg CO2 eq.  2,34*10-5
  4                                TOTAL                 kg CO2 eq.  3,41*10-2
  5                                                      kg SO2 eq.  1,17*10-4
  6                                                  3- eq.\nkg PO4  6,55*10-5
  7                                                    kg NMVOC eq.  9,06*10-5
  8                                                       kg Sb eq.  6,12*10-8
  9                                       MJ, net calorific \nvalue      0,430
  10                                                         m3 eq.  7,86*10-3
  0                                 UNIT                   Upstream       Core
  1                                   kg                  1,22*10-6  1,04*10-6
  2                                   kg                  1,37*10-2  1,03*10-3
  3                                   kg                  1,62*10-6   2,4*10-7
  0                                 UNIT                   Upstream       Core
  1                                   kg                   1,2*10-6  9,42*10-7
  2                                   kg                  1,26*10-2  1,07*10-3
  3                                   kg                  1,59*10-6  2,48*10-7

                   4               5           6          7
  0             Core  TOTAL\nat gate  Downstream      TOTAL
  1        4,63*10-3       3,86*10-2   3,17*10-2  7,03*10-2
  2        4,32*10-5       1,19*10-3   5,42*10-6  1,20*10-3
  3        8,66*10-7       2,44*10-5   4,98*10-6  2,94*10-5
  4        4,68*10-3       3,98*10-2   3,17*10-2  7,15*10-2
  5        1,74*10-5       1,36*10-4   7,38*10-5  2,10*10-4
  6        7,23*10-6       7,42*10-5   3,19*10-5  1,06*10-4
  7        1,25*10-5       1,07*10-4   7,88*10-5  1,86*10-4
  8        6,45*10-9       7,14*10-8   4,67*10-8  1,18*10-7
  9            0,065           0,508       0,205      0,712
  10       9,45*10-4       9,27*10-3   2,34*10-3  1,16*10-2
  0             Core  TOTAL\nat gate  Downstream      TOTAL
  1        4,58*10-3       3,76*10-2   9,89*10-3  4,75*10-2
  2        3,86*10-5       1,12*10-3   4,86*10-6  1,12*10-3
  3        8,54*10-7       2,42*10-5   4,06*10-6  2,83*10-5
  4        4,62*10-3       3,88*10-2   9,90*10-3  4,87*10-2
  5        1,74*10-5       1,34*10-4   1,06*10-4  2,39*10-4
  6        7,09*10-6       7,25*10-5   1,53*10-5  8,79*10-5
  7        1,28*10-5       1,03*10-4    9,3*10-5  1,96*10-4
  8        6,63*10-9       6,79*10-8   2,71*10-8   9,5*10-8
  9            0,064           0,494       0,136      0,630
  10       9,13*10-4       8,77*10-3   8,99*10-4  9,67*10-3
  0   TOTAL\nat gate      Downstream       TOTAL        NaN
  1        2,26*10-6       1,54*10-7   2,41*10-6        NaN
  2        1,48*10-2       1,15*10-2   2,62*10-2        NaN
  3        1,86*10-6       1,42*10-6   3,28*10-6        NaN
  0   TOTAL\nat gate      Downstream       TOTAL        NaN
  1        2,14*10-6       9,81*10-8   2,24*10-6        NaN
  2        1,36*10-2       3,02*10-3   1,67*10-2        NaN
  3        1,84*10-6       9,66*10-7    2,8*10-6        NaN  ,
  'file_name': 'epd2113.pdf'},
 {'dataFrame':                                           0             1          2   \
  0           Parameter \nAbbreviation \nUnits
  1                      Environmental impacts
  2                Climate change – GWP fossil    GWP-fossil  kg CO2 eq
  3              Climate change – GWP biogenic  GWP-biogenic  kg CO2 eq
  4   Climate change – GWP land transformation     GWP-luluc  kg CO2 eq
  ..                                       ...           ...        ...
  4                                                                Unit
  5                                                      CFR         kg
  6                                                      MFR         kg
  7                                                      MER         kg
  8                                                       EE         MJ

            3         4         5         6         7         8         9   \
  0        NaN       NaN       NaN       NaN       NaN       NaN       NaN
  1        NaN       NaN       NaN       NaN       NaN       NaN       NaN
  2        NaN       NaN       NaN       NaN       NaN       NaN       NaN
  3        NaN       NaN       NaN       NaN       NaN       NaN       NaN
  4        NaN       NaN       NaN       NaN       NaN       NaN       NaN
  ..       ...       ...       ...       ...       ...       ...       ...
  4    A1 - A3        A4        A5        C1        C2        C3        C4
  5   0.00E+00  0.00E+00  0.00E+00  0.00E+00  0.00E+00  0.00E+00  0.00E+00
  6   2.51E-03  2.00E-04  6.23E-04  4.79E-05  1.34E-04  0.00E+00  1.73E-04
  7   1.70E-04  0.00E+00  4.09E-05  2.13E-06  2.31E-06  0.00E+00  5.79E-07
  8   0.00E+00  0.00E+00  2.84E-02  0.00E+00  0.00E+00  0.00E+00  2.84E+00

            10
  0        NaN
  1        NaN
  2        NaN
  3        NaN
  4        NaN
  ..       ...
  4          D
  5   0.00E+00
  6   0.00E+00
  7   0.00E+00
  8   0.00E+00

  [177 rows x 11 columns],
  'file_name': 'epd2270.pdf'},
 {'dataFrame':                 0               1                  2                 3
  0                  BCF PA6 \n(1C)  BCF PA6 \n(2E+2F)  BCF PA6.6 \n(3C)
  1     GWP – Total        8,65E+00           9,02E+00          8,00E+00
  2    GWP – Fossil        8,58E+00           8,87E+00          7,90E+00
  3  GWP – Biogenic        7,53E-02           1,43E-01          9,56E-02
  4     GWP – Luluc        2,72E-03           2,44E-03          4,18E-03
  5       GWP – GHG        8,58E+00           8,88E+00          7,90E+00,
  'file_name': 'epd454.pdf'}]