In [1]:
import camelot
# tables = camelot.read_pdf('epd1388_2021.pdf', pages='10',process_background=True)
# tables = camelot.read_pdf('./IBU-09-20/New/14632.pdf', pages='6', split_text=True,table_areas=["69.60548391889084,500.088593765987,525.3099336281931,403.96614296894364"])
# print(len(tables))

tables = camelot.read_pdf('./New/14987.pdf', pages='6')
print(len(tables))

4

In [3]:
df = tables[1].df
df

,0,1,2,3,4,5,6,7
0,Core Indicator,Unit,A1-A3,C1,C2,C3,C4,D
1,Global warming potential - total,[kg CO2-Eq.],4.91E-1,2.56E-3,6.58E-4,2.55E-4,1.74E-3,-1.23E-1
2,Global warming potential - fossil fuels,[kg CO2-Eq.],4.91E-1,2.54E-3,6.53E-4,2.53E-4,1.74E-3,-1.23E-1
3,Global warming potential - biogenic,[kg CO2-Eq.],0.00E+0,0.00E+0,0.00E+0,0.00E+0,0.00E+0,0.00E+0
4,GWP from land use and land use change,[kg CO2-Eq.],3.13E-4,2.07E-5,5.33E-6,1.73E-6,1.41E-6,3.50E-6
5,Depletion potential of the stratospheric ozone...,[kg CFC11-Eq.],1.75E-11,4.69E-19,1.21E-19,6.14E-19,3.95E-18,2.68E-16
6,"Acidification potential, accumulated exceedance",[mol H+-Eq.],1.11E-3,1.29E-5,4.02E-6,2.49E-6,5.27E-6,-2.73E-4
7,"Eutrophication, fraction of nutrients reaching...",[kg PO4-Eq.],1.18E-6,7.78E-9,2.00E-9,7.38E-10,3.19E-7,-6.95E-8
8,"Eutrophication, fraction of nutrients reaching...",[kg N-Eq.],2.81E-4,6.13E-6,1.94E-6,1.21E-6,1.17E-6,-4.99E-5
9,"Eutrophication, accumulated exceedance",[mol N-Eq.],2.89E-3,6.80E-5,2.15E-5,1.33E-5,1.28E-5,-5.05E-4
10,Formation potential of tropospheric ozone phot...,[kg NMVOC-Eq.],8.59E-4,1.25E-5,3.75E-6,3.52E-6,3.81E-6,-2.06E-4
11,Abiotic depletion potential for non-fossil res...,[kg Sb-Eq.],1.32E-5,2.06E-10,5.32E-11,2.77E-10,1.18E-10,-1.99E-6
12,Abiotic depletion potential for fossil resources,[MJ],6.52E+0,3.41E-2,8.78E-3,4.95E-3,2.50E-2,-1.06E+0
13,"Water (user) deprivation potential, deprivatio...",[m³ world-Eq \ndeprived],1.77E-2,2.49E-5,6.42E-6,4.88E-5,-1.95E-5,-9.25E-3

In [37]:
searchfor = ['^.*Global.*$', '^.*GWP.*$']
df[df[0].str.contains('|'.join(searchfor)) | df[1].str.contains('TEST')]

,0,1,2,3,4,5,6,7
1,Global warming potential - total,[kg CO2-Eq.],4.91E-1,2.56E-3,6.58E-4,2.55E-4,1.74E-3,-1.23E-1
2,Global warming potential - fossil fuels,[kg CO2-Eq.],4.91E-1,2.54E-3,6.53E-4,2.53E-4,1.74E-3,-1.23E-1
3,Global warming potential - biogenic,[kg CO2-Eq.],0.00E+0,0.00E+0,0.00E+0,0.00E+0,0.00E+0,0.00E+0
4,GWP from land use and land use change,[kg CO2-Eq.],3.13E-4,2.07E-5,5.33E-6,1.73E-6,1.41E-6,3.50E-6

In [23]:
if not df[df[0].str.contains('|'.join(searchfor)) | df[1].str.contains('^\[kg')].empty:
    print("A")

A

In [35]:
df[df[0].str.contains("^.*fraction.*$")]

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []

In [4]:
tables[2].df

,0,1,2,3,4,5,6,7
0,Indicator,Unit,A1-A3,C1,C2,C3,C4,D
1,Renewable primary energy as energy carrier,[MJ],9.53E-1,1.97E-3,5.08E-4,3.57E-4,1.76E-3,8.18E-2
2,Renewable primary energy resources as material...,[MJ],1.67E-1,0.00E+0,0.00E+0,0.00E+0,0.00E+0,0.00E+0
3,Total use of renewable primary energy resources,[MJ],1.12E+0,1.97E-3,5.08E-4,3.57E-4,1.76E-3,8.18E-2
4,Non-renewable primary energy as energy carrier,[MJ],5.80E+0,3.42E-2,8.82E-3,7.33E-1,2.50E-2,-1.06E+0
5,Non-renewable primary energy as material utili...,[MJ],7.28E-1,0.00E+0,0.00E+0,-7.28E-1,0.00E+0,0.00E+0
6,Total use of non-renewable primary energy reso...,[MJ],6.53E+0,3.42E-2,8.82E-3,4.95E-3,2.50E-2,-1.06E+0
7,Use of secondary material,[kg],6.04E-3,0.00E+0,0.00E+0,0.00E+0,0.00E+0,7.26E-2
8,Use of renewable secondary fuels,[MJ],0.00E+0,0.00E+0,0.00E+0,0.00E+0,0.00E+0,0.00E+0
9,Use of non-renewable secondary fuels,[MJ],0.00E+0,0.00E+0,0.00E+0,0.00E+0,0.00E+0,0.00E+0
10,Use of net fresh water,[m³],1.04E-3,2.30E-6,5.92E-7,1.39E-6,3.07E-7,-2.17E-4

In [5]:
tables[3].df

,0,1,2,3,4,5,6,7
0,Indicator,Unit,A1-A3,C1,C2,C3,C4,D
1,Hazardous waste disposed,[kg],1.42E-8,1.58E-9,4.08E-10,1.30E-10,9.12E-11,-1.35E-7
2,Non-hazardous waste disposed,[kg],4.51E-3,5.42E-6,1.40E-6,1.34E-6,2.40E-2,1.26E-2
3,Radioactive waste disposed,[kg],1.07E-4,6.30E-8,1.62E-8,6.54E-8,3.01E-7,3.75E-8
4,Components for re-use,[kg],0.00E+0,0.00E+0,0.00E+0,0.00E+0,0.00E+0,0.00E+0
5,Materials for recycling,[kg],0.00E+0,0.00E+0,0.00E+0,7.26E-2,0.00E+0,0.00E+0
6,Materials for energy recovery,[kg],2.08E-3,0.00E+0,0.00E+0,0.00E+0,0.00E+0,0.00E+0
7,Exported electrical energy,[MJ],0.00E+0,0.00E+0,0.00E+0,0.00E+0,0.00E+0,0.00E+0
8,Exported thermal energy,[MJ],0.00E+0,0.00E+0,0.00E+0,0.00E+0,0.00E+0,0.00E+0

In [6]:
tables = camelot.read_pdf('./New/14987.pdf', pages='all')
print(len(tables))

9

In [16]:
tables[7].df

,0,1,2,3,4,5,6,7
0,Indicator,Unit,A1-A3,C1,C2,C3,C4,D
1,Hazardous waste disposed,[kg],1.42E-8,1.58E-9,4.08E-10,1.30E-10,9.12E-11,-1.35E-7
2,Non-hazardous waste disposed,[kg],4.51E-3,5.42E-6,1.40E-6,1.34E-6,2.40E-2,1.26E-2
3,Radioactive waste disposed,[kg],1.07E-4,6.30E-8,1.62E-8,6.54E-8,3.01E-7,3.75E-8
4,Components for re-use,[kg],0.00E+0,0.00E+0,0.00E+0,0.00E+0,0.00E+0,0.00E+0
5,Materials for recycling,[kg],0.00E+0,0.00E+0,0.00E+0,7.26E-2,0.00E+0,0.00E+0
6,Materials for energy recovery,[kg],2.08E-3,0.00E+0,0.00E+0,0.00E+0,0.00E+0,0.00E+0
7,Exported electrical energy,[MJ],0.00E+0,0.00E+0,0.00E+0,0.00E+0,0.00E+0,0.00E+0
8,Exported thermal energy,[MJ],0.00E+0,0.00E+0,0.00E+0,0.00E+0,0.00E+0,0.00E+0

In [17]:
tables = camelot.read_pdf('./New/14632.pdf', pages='all')
print(len(tables))

FileNotFoundError: [Errno 2] No such file or directory: './New/14632.pdf'